//
//  WinLibrary.h
//  Readium
//
//  Created by Jim Dovey on 2013-09-26.
//  Copyright (c) 2012-2013 The Readium Foundation and contributors.
//  
//  The Readium SDK is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//  
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//  
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifndef __Readium_Library_h__
#define __Readium_Library_h__

#include "Readium.h"
#include <ePub3/library.h>

using ::Platform::String;
using ::Windows::Storage::IStorageFile;
using ::Windows::Foundation::IAsyncOperation;
using ::Windows::Foundation::IAsyncAction;
using ::Windows::Foundation::Uri;

BEGIN_READIUM_API

ref class Container;
ref class Package;
ref class ManifestItem;
ref class CFI;
interface class IClosableStream;

/**
  <summary>
  <para>
  This is a library in the smallest sense: it keeps track of ePub files
  by their unique-identifier, storing the path to that ePub file *as given*. Its
  primary presence here is to allow for inter-publication linking. It is also
  designed to be subclassed in order to serve as the basis of a complete library
  in an application, with all the additional functionality that would involve.
  </para>
  <para>
  Note that each application would have a single library, accessible only through
  the MainLibrary() static method. A library can optionally be written out to
  disk and then loaded back in by calling MainLibrary() with a Locator instance
  at application startup. Once the singleton instance has been created,
  MainLibrary() will ignore its argument and always return that instance.
  </para>
  </summary>
  <remarks>
  Thoughts: OCF allows for multiple packages to be specified, but I don't see any
  handling of that in ePub3 CFI?
  </remarks>
 */
public ref class Library sealed
{
private:
	/// Creates a library object from a native Library.
	Library(::ePub3::Library* native);

public:
	/// Creates or returns the singleton Library instance.
	static Library^ MainLibrary();

	/// Returns the singleton Library instance by loadin from a saved file.
	/// <param name="savedLibrary">A file generated by WriteToFile().</param>
	/// <returns>The single Library instance for this application.</returns>
	static IAsyncOperation<Library^>^ LoadLibrary(IStorageFile^ savedLibrary);

	virtual ~Library() {}

	/// Returns the location of a known ePub file corresponding to a Unique ID.
	/// <param name="uniqueID">The unique ID of a Package object.</param>
	/// <returns>A file object, or nullptr if the unique ID is unknown.</results>
	IAsyncOperation<IStorageFile^>^ FileForEPubWithUniqueID(String^ uniqueID);

	/// Returns the location of a known ePub file corresponding to a Package ID.
	/// <param name="uniqueID">The package ID of a Package object.</param>
	/// <returns>A file object, or nullptr if the package ID is unknown.</results>
	IAsyncOperation<IStorageFile^>^ FileForEPubWithPackageID(String^ packageID);

	void AddPublicationsInContainer(Container^ container, IStorageFile^ file);
	IAsyncAction^ AddPublicationsInContainer(IStorageFile^ file);

	Uri^ EPubURLForPublication(Package^ pkg);
	Uri^ EPubURLForPackageID(String^ packageID);

	IAsyncOperation<Package^>^ LoadPackage(Uri^ epubURL);
	IAsyncOperation<Package^>^ LoadPackage(Uri^ ePubURL, bool allowLoad);

	Uri^ EPubCFIURLForManifestItem(ManifestItem^ item);
	ManifestItem^ ManifestItemForCFIURL(Uri^ urlWithCFI, _Out_ CFI^ remainingCFI);
	IClosableStream^ StreamForEPubURL(Uri^ urlWithCFI, _Out_ CFI^ remainingCFI);

	IAsyncAction^ WriteToFile(IStorageFile^ file);

};

END_READIUM_API

#endif	/* __Readium_Streams_h__ */
